### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by beojan** [dguest/pandamonium#16]
```
File "/home/stanislaus/.local/bin/pandamon", line 108
                                streams = {ds['streamname']: ds for ds in datasets}
                                                                  ^                                            SyntaxError: invalid syntax                  
```

The spacing is weird because I'm on a phone.

**Comment by dguest** [comment]
my guess is that you're using an older version of python that doesn't support set comprehension. I think they were introduced in 2.7, whereas a lot of older operating systems might still use 2.6 by default.
