### ISSUE TITLE
failure to resub in panda 1.4.8

### ISSUE THREAD

**Issue by neilwarrack** [dguest/pandamonium#17]
I love pandamonium - thanks for creating it! I just tried to `--resub` and saw an error I've not seen before. I'm using panda 1.4.8 and the error looks like this:
```
Traceback (most recent call last):
  File "/afs/cern.ch/user/n/nwarrack/pandamonium/panda-resub-taskid", line 73, in <module>
    retry(jobs, args)
  File "/afs/cern.ch/user/n/nwarrack/pandamonium/panda-resub-taskid", line 36, in retry
    pbook = PBookCore.PBookCore(False, False, False)
TypeError: __init__() takes at most 2 arguments (4 given)
```
Is anyone still maintaining this? Help needed?

**Comment by dguest** [comment]
Hi,

Actually I just saw the same bug, I'm trying to fix it now.

**Comment by jburzy01** [comment]
Hi @dguest, this bug exists in panda-kill-taskid as well

**Comment by dguest** [comment]
ok I'll take a look tomorrow. It should be pretty easy to fix so if you get it running in the meantime feel free to make a pull request.
