### ISSUE TITLE
Support working group and official datsets (e.g. phys-hdbs, group.phys-hdbs)?

### ISSUE THREAD

**Issue by cjustin88** [dguest/pandamonium#20]
I submit jobs with group credentials and output "official" group datasets, for example:

https://bigpanda.cern.ch/task/20653237/
with output container group.phys-`hdbs.20200222_4515a4a0_U.ZdZd13TeV.bkg_mc16e_ttH_NTUP4L/`.

Such output containers are not listed with `pandamon -s` or `pandamon phys.hdbs`. Is this supported?

Thanks,
Justin

**Comment by dguest** [comment]
Can you try it with `-u ''` (that's an empty string in quotes)? It might just be that your user name isn't set, you can set the environment variable `GRID_USER_NAME` to be your full user name.

**Comment by justin2net** [comment]
`pandamon` only lists jobs under my own name, e.g. `user.ychiu....`
(same with `pandamon -s` and `pandamon -u''`)

**Comment by cjustin88** [comment]
`pandamon` only lists jobs under my own name, e.g. `user.ychiu....`
(same with `pandamon -s` and `pandamon -u''`)

**Comment by dguest** [comment]
right can you try `pandamon group.phys-hdbs -u ''`? I get a lot of jobs listed with that. In fact maybe you should omit the `-u ''` since you might have your user name set right to begin with, it sounds like you were just using the wrong beginning of the job name.

**Comment by cjustin88** [comment]
Thanks! `pandamon group.phys-hdbs -u ''` and `pandamon group.phys-hdbs` both work. I thought I had to pass `phys-hdbs` as the username.

**Comment by dguest** [comment]
The positional argument is actually the task name. If you end it without a trailing slash `pandamon` will append a wildcard (`*`), but in general it uses the same syntax that a panda task query would use. You can also use wildcards in the task name.
