### ISSUE TITLE
make pandamonium this pip-installable

### ISSUE THREAD

**Issue by lukasheinrich** [dguest/pandamonium#26]
I wanna `pip install pandamonium` :)

**Comment by dguest** [comment]
Me Too!

**Comment by matthewfeickert** [comment]
> I wanna `pip install pandamonium` :)

Yesssssssssssss! 

Sadly, the name is already taken: https://pypi.org/project/pandamonium/ :sob: But there hasn't been any activity on the PyPI page or the GitHub page for 3 years. @dguest you could very nicely ask @Ffisegydd if they would consider giving you the PyPI namespace.

If so, I'm happy to help with the setup.

**Comment by beojan** [comment]
Ideally you could get the name (I just accidentally installed the wrong package), but if not, maybe `pandamon`, or `atlas-pandamon`?

**Comment by Ffisegydd** [comment]
Sorry I saw this notification and thought it sounded like a great idea (my package is dead) but it just fell off my radar. @dguest  I'd be happy to either delete the project, then you could register the name.

Let me know if/when you're ready to do this by pinging me here and I'll delete it. Don't want to delete it until you're ready in case it gets snatched by a third party - unlikely, but not impossible.

**Comment by dguest** [comment]
Paging Dr. @matthewfeickert. For what it's worth, having a pip installer is more 20 more rad than having a DOI, so if you want to lead us to glory I'll backseat-drive you toward pip.

**Comment by matthewfeickert** [comment]
> so if you want to lead us to glory I'll backseat-drive you toward pip.

I can work on making a PR that will make everything a proper Python library and then expose a CLI that has the same behavior as there is now. I think once that is ready and it can actually be `pip` installed then @dguest should talk with @Ffisegydd about getting transfer of the PyPI namespace (thanks again @Ffisegydd for being so cool about all of this).

**Comment by Ffisegydd** [comment]
I'm not realistically going to use the name so would rather it go to a project that is going to use it and it'll be useful for.

Just ping me here when you'd like me to drop it :)

**Comment by matthewfeickert** [comment]
> Just ping me here when you'd like me to drop it :)

@Ffisegydd now that PR #29 is in I think we're ready. Can you please transfer permissions for https://pypi.org/project/pandamonium/ to @dguest?

**Comment by Ffisegydd** [comment]
Done, sorry it took me a few days. Once you're all sorted you should be able to remove me as an Owner and take control of the name.

**Comment by matthewfeickert** [comment]
> Done, sorry it took me a few days. Once you're all sorted, you should be able to remove me as an Owner and take control of the name.

Thank you so much @Ffisegydd! This is great to have done and I've put a `v0.0.1` up there for the time being until we cut a new release! We really want to thank you for your generosity, so if you have a PayPal or something that you'd feel comfortable sharing with us over email I'd like to send you a coffee at least. :)

<I'm going to leave this Issue open until I add in the CI to do this auotmatically and we cut a new release, but @lukasheinrich you can now `pip install pandamonium`!>

**Comment by Ffisegydd** [comment]
I'm glad to help. I wasn't going to use the PyPI name, so better another project makes use of it.

Don't worry about Paypal or anything like that. From a brief look at your project, it looks like it helps with using scientific data pandas? As an ex-physics academic and a now data scientist, I'm glad to support a project that makes working with scientific data easier!

Let me know if you need anything else from me by pinging me here, I'll assume as a joint Owner you'll be able to remove me when ready, but if not let me know, and I'll remove myself.

**Comment by matthewfeickert** [comment]
> From a brief look at your project, it looks like it helps with using scientific data with pandas?

@Ffisegydd Actually, PanDA &mdash; the ATLAS experiment's [Production and Distributed Analysis System](https://twiki.cern.ch/twiki/bin/view/PanDA/PanDA) &mdash; the names are rightfully confusing. `pandamonium` gives us a higher level CLI tool to interact with our compute jobs that are running on the [Worldwide LHC Computing Grid](https://wlcg-public.web.cern.ch/) (WLCG) which we would normally have to use the PanDA web UI (https://bigpanda.cern.ch/) to deal with or the lower level `pandatools` API.

> As an ex-physics academic and a now data scientist, I'm glad to support a project that makes working with scientific data easier!

Well thanks. :slightly_smiling_face: We really do appreciate it and you've been a great help. We've removed you from the PyPI account so we should be good to go. :+1: See you around GitHub!

**Comment by matthewfeickert** [comment]
@lukasheinrich This is now officially done and clear of the old releases now that `pandamomium` [`v0.2.1` is up on PyPI](https://pypi.org/project/pandamonium/0.2.1/#history). :+1:
