### ISSUE TITLE
Get Zenodo DOI

### ISSUE THREAD

**Issue by matthewfeickert** [dguest/pandamonium#27]
I want to be able to credit (...and cite?) `pandamonium` properly. It would help a lot if there was a [Zenodo](https://zenodo.org/) DOI for it. @dguest As I've done this for multiple other projects let me know if I can help.

**Comment by dguest** [comment]
No objection from me!

I wrote this as a demonstration of the awesomeness of the panda api, to try to get more people to use it so that the panda api could become even more awesome. But hey, let's make it a proper Thing!

**Comment by matthewfeickert** [comment]
@dguest It would be nice for PR #26 if that was release `v0.0.2` and if a `v0.0.1` already existed. Once you have a Zenodo account setup and linked to your GitHub account with tracking for this repo turned on (ping me if you have questions) can you cut a release `v0.0.1` off of the branch `python2`?

**Comment by matthewfeickert** [comment]
@dguest took care of this and now there's a DOI! Yay! [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.4019463.svg)](https://doi.org/10.5281/zenodo.4019463)
