### ISSUE TITLE
Taskid/Pandaid confusion?

### ISSUE THREAD

**Issue by mswiatlo** [dguest/pandamonium#49]
HI, 

I recently found that restarting jobs via the TaskID returned by pbook (with -t) has started to fail; this number apparently instead is corresponding to the PandaID. PBook used to be smart and accept either the TaskID or PandaID for the restart of the job, but now it really is demanding the TaskID. Can we change what is returned? Asoka said:

> retry(taskid), not retry(pandaid).  the task for the above is 23611708
> 
> (or you can use the reqID when you do a show() from pbook).

Does this request make sense or am I doing something wrong?

Cheers,
Max

**Comment by mswiatlo** [comment]
For what it's worth I've adjusted my restart script to just do:

pandamon -d 31 -i failed  -a | awk '{print $2}' | panda-resub-taskid -n 1

And this works fine. So the -a option is already retrieving the right information.

**Comment by dguest** [comment]
This probably makes sense. I blame @lawrenceleejr because [the thing returned by `-t`][1] is apparently `'reqid'`, which sounds like another thing entirely. Larry was this your idea or mine? Why did we do it?

Anyway, sounds like the Danny Antrim option saves the day again. I mean, why would you ever _not_ use the @dantrim option?

[1]: https://github.com/dguest/pandamonium/blob/d6457c8f302d949d732968cf8641a8d13146113b/src/pandamonium/pandamon.py#L251

**Comment by matthewfeickert** [comment]
> This probably makes sense. I blame @lawrenceleejr because [the thing returned by `-t`](https://github.com/dguest/pandamonium/blob/d6457c8f302d949d732968cf8641a8d13146113b/src/pandamonium/pandamon.py#L251) is apparently `'reqid'`, which sounds like another thing entirely. Larry was this your idea or mine? Why did we do it? Can we change it to `'jeditaskid'`?

Regardless we should make sure this is better documented as

```
$ pandamon --help | grep taskid
  -t, --taskid          output only taskid. useful for piping.
```

doesn't make this clear.

**Comment by lawrenceleejr** [comment]
Totally agree. Looks like my fault. Indeed the reqid used to work in practice but probably should have always been the actual task ID. Almost definitely me not understanding the difference (still).

**Comment by matthewfeickert** [comment]
> Almost definitely me not understanding the difference (still).

You aren't alone @lawrenceleejr. Is there public documentation on the difference between the two?

**Comment by dguest** [comment]
How about I just change it to give the Jedi Tas Kid?

**Comment by mswiatlo** [comment]
Yeah, I don’t think the other one is useful for anything anymore.

**Comment by mswiatlo** [comment]
(And this isn’t anyone here’s fault per se— both used to work, and the change was unannounced as usual. Normal panda development fun!)

**Comment by matthewfeickert** [comment]
> Is there public documentation on the difference between the two?

From the [PanDA JEDI docs](https://twiki.cern.ch/twiki/bin/view/PanDA/PandaJEDI?rev=263)

> `JEDITASKID` is the unique task identifier in JEDI. It comes from `ATLAS_DEFT.PRODSYS2_TASK_ID_SEQ` independently of `T_TASK_REQUEST.REQID`. Until `DEFT` is ready task requests come from `AKTR` `T_TASK_REQUEST.REQID` is stored in `JEDI_TASKS.REQID` which is mapped to `job.TASKID`.

So not super clear, but at least draws a distinciton.
