### ISSUE TITLE
panda-client renamed pandatools to pandaclient

### ISSUE THREAD

**Issue by kratsg** [dguest/pandamonium#57]
See PanDAWMS/panda-client@eee3914e78347a427ae80a2588d181a6b8632dfb.

./cc @tmaeno which doesn't make sense as this is released as a patch release, but with API-breaking changes.

**Comment by matthewfeickert** [comment]
Thanks @kratsg. @dguest and I will patch this and release a new minor release `v0.3.0` for this.
